#!/bin/bash
CMD_PATH=`dirname $0`
cd $CMD_PATH

pod spec lint ACComponentItemMessage.podspec --sources='git@192.168.202.61:root/linewell-specs.git,git@github.com:aliyun/aliyun-specs.git,https://github.com/CocoaPods/Specs'  --allow-warnings --verbose #--use-libraries

exit 0
