#!/bin/bash
CMD_PATH=`dirname $0`
cd $CMD_PATH

# 删除旧的tag
echo '---开始删除旧的版本---'
git tag -d 2.0.0
git push origin :refs/tags/2.0.0
echo '---结束删除旧的版本---'

# 推送新的版本到远程仓库
echo '---开始创建新的tag并推送到远程仓库---'
git tag 2.0.0
git push --tags
echo '---结束创建新的tag并推送到远程仓库---'
exit 0
